#!/bin/bash

# Clean up the terminal first
clear && reset

USER=$(logname)
REPOSITORY="https://www.github.com/mattunlv/ProcessJ.git"

## -----------
## Directories

INSTALL_DIRECTORY="~/ProcessJ"
WORKING_DIRECTORY="~/workingpj"

## ----------
## File Paths

CONFIGURATION_PATH="~/processjrc"

COMPILER_PATH="$INSTALL_DIRECTORY/pjc"
EXECUTOR_PATH="$INSTALL_DIRECTORY/pj"

echo "Creating configuration file."
touch $CONFIGURATION_PATH

# Set the license
echo "## Licensed to the Apache Software Foundation (ASF) under one or more"         >> $CONFIGURATION_PATH
echo "## contributor license agreements.  See the NOTICE file distributed with"      >> $CONFIGURATION_PATH
echo "## this work for additional information regarding copyright ownership."        >> $CONFIGURATION_PATH
echo "## The ASF licenses this file to You under the Apache Licence, Version 2.0"    >> $CONFIGURATION_PATH
echo "## (the "License"); you may not use this file except in compliance with"       >> $CONFIGURATION_PATH
echo "## the License. You may obtain a copy of the License at"                       >> $CONFIGURATION_PATH
echo "##"                                                                            >> $CONFIGURATION_PATH
echo "##    http://www.apache.org/licenses/LICENSE-2.0"                              >> $CONFIGURATION_PATH
echo "##"                                                                            >> $CONFIGURATION_PATH
echo "## Unless required by applicable law or agree to in writing, software"         >> $CONFIGURATION_PATH
echo "## distributed under the License is ditributed on an "AS IS" BASIS,"           >> $CONFIGURATION_PATH
echo "## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either expressed or implied." >> $CONFIGURATION_PATH
echo "## See the License for the specific language governing permissions and"        >> $CONFIGURATION_PATH
echo "## limitations under the License."                                             >> $CONFIGURATION_PATH
echo ""                                                                              >> $CONFIGURATION_PATH
echo "workingdir=workingpj"                                                          >> $CONFIGURATION_PATH
echo "installdir=$INSTALL_DIRECTORY"                                                 >> $CONFIGURATION_PATH

# Clone the repository into the install directory
echo "Retrieving from $REPOSITORY"
git clone $REPOSITORY $INSTALL_DIRECTORY > /dev/null 2>&1

# Build
cd $INSTALL_DIRECTORY
echo "Building...."
ant > /dev/null

